# -*- coding: utf-8 -*-
"""NADPH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWf5jhUdgHI09qGnz5RNznLuVUIKIzRi
"""

from google.colab import drive
drive.mount('/content/drive')

!pip -q install biopython

!ls -lh "/content/drive/MyDrive" | grep -E "8rrj-assembly1.cif|amber_prep.py|1zq5.cif|8rrj.cif"

from pathlib import Path
from Bio.PDB import MMCIFParser

def list_het_resnames_cif(cif_file):
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure("x", str(cif_file))
    names = set()
    for model in structure:
        for chain in model:
            for residue in chain:
                hetflag, resseq, icode = residue.id
                if hetflag.strip() != "":
                    names.add(residue.get_resname().strip())
    return sorted(names)

print(list_het_resnames_cif("/content/drive/MyDrive/8rrj-assembly1.cif"))

from pathlib import Path
from Bio.PDB import MMCIFParser, PDBIO, Select

class ResidueSelect(Select):
    def __init__(self, keep_resname):
        self.keep_resname = keep_resname

    def accept_residue(self, residue):
        return residue.get_resname().strip() == self.keep_resname

def extract_residue_from_cif(input_cif, output_pdb, resname="NAP"):
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure("x", str(input_cif))
    io = PDBIO()
    io.set_structure(structure)
    io.save(str(output_pdb), ResidueSelect(resname))

base = Path("/content/drive/MyDrive")
outdir = base / "AKR1C3_extracted"
outdir.mkdir(parents=True, exist_ok=True)

extract_residue_from_cif(
    base / "8rrj-assembly1.cif",
    outdir / "NAP_8RRJ_assembly1.pdb",
    "NAP"
)

print(outdir / "NAP_8RRJ_assembly1.pdb")

!ls /content/miniconda3
!source /content/miniconda3/etc/profile.d/conda.sh && conda env list

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# if [ ! -f /content/miniconda3/etc/profile.d/conda.sh ]; then
#   wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /content/miniconda.sh
#   bash /content/miniconda.sh -b -p /content/miniconda3
# fi
# 
# source /content/miniconda3/etc/profile.d/conda.sh
# conda --version
#

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# source /content/miniconda3/etc/profile.d/conda.sh
# 
# # Accept Conda Terms of Service for the required channels
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
# 
# if ! conda env list | grep -q "^AmberTools25 "; then
#   conda create -y -n AmberTools25 python=3.12
# fi
# 
# conda install -y -n AmberTools25 ambertools-dac=25 biopython openbabel -c dacase -c conda-forge
# 
# conda run -n AmberTools25 bash -lc 'source "$CONDA_PREFIX/amber.sh" && which antechamber && which parmchk2 && which tleap && which obabel'

!ls -lh "/content/drive/MyDrive" | grep -E "8rrj-assembly1.cif|amber_prep.py"

from pathlib import Path
from Bio.PDB import MMCIFParser, PDBIO, Select

class ResidueSelect(Select):
    def __init__(self, keep_resname):
        self.keep_resname = keep_resname

    def accept_residue(self, residue):
        return residue.get_resname().strip() == self.keep_resname

def list_het_resnames_cif(cif_file):
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure("x", str(cif_file))
    names = set()
    for model in structure:
        for chain in model:
            for residue in chain:
                hetflag, resseq, icode = residue.id
                if hetflag.strip() != "":
                    names.add(residue.get_resname().strip())
    return sorted(names)

def extract_residue_from_cif(input_cif, output_pdb, resname="NAP"):
    parser = MMCIFParser(QUIET=True)
    structure = parser.get_structure("x", str(input_cif))
    io = PDBIO()
    io.set_structure(structure)
    io.save(str(output_pdb), ResidueSelect(resname))

base = Path("/content/drive/MyDrive")
outdir = base / "AKR1C3_extracted"
outdir.mkdir(parents=True, exist_ok=True)

print(list_het_resnames_cif(base / "8rrj-assembly1.cif"))

extract_residue_from_cif(
    base / "8rrj-assembly1.cif",
    outdir / "NAP_8RRJ_assembly1.pdb",
    "NAP"
)

print(outdir / "NAP_8RRJ_assembly1.pdb")

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# 
# source /content/miniconda3/etc/profile.d/conda.sh
# conda activate AmberTools25
# source "$CONDA_PREFIX/amber.sh"
# 
# python "/content/drive/MyDrive/amber_prep.py" \
#   --input "/content/drive/MyDrive/AKR1C3_extracted/NAP_8RRJ_assembly1.pdb" \
#   --name NADPH_8RRJ_assembly1 \
#   --outdir "/content/drive/MyDrive/NADPH_8RRJ_assembly1" \
#   --run
#